/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home_filled =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home_lineal =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData igtv = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData like_fill =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData like_lineal =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData paper_plane =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData photo_camera =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData people_fill =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData profile_lineal =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData search_fill =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search_lineal =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData bookmark_lineal =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData bookmark_fill =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe80e, fontFamily: _kFontFam);
}
