/// Flutter icons HomeFilled
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeFilled
///      fonts:
///       - asset: fonts/HomeFilled.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeFilled {
  HomeFilled._();

  static const _kFontFam = 'HomeFilled';

  static const IconData home_filled = const IconData(0xe800, fontFamily: _kFontFam);
}
